<?xml version="1.0" encoding="utf-8"?>
<!--DON'T FORGET TO UPDATE THE DYNAMIS VERSION TOO-->
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
    <PropertyGroup>
        <Version>0.0.0.28</Version>
        <Description>Gaolbreak UI</Description>
        <PackageProjectUrl>https://github.com/sourpuh/ffxiv_gaolbreak</PackageProjectUrl>
        <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="TerraFX.Interop.Windows" />
        <PackageReference Include="YamlDotNet" Version="16.3.0" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\Content\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Visible>false</Visible>
        </Content>
    </ItemGroup>
</Project>
