version: 1

# ImGui window IDs that should stay in the FG.
foregroundWindowIds:
  - 0x88AE4BAD # Gaolbreak ###GaolbreakIndicator
  - 0xE73BC75C # ResPls ##rezRects

# ImGui window name prefixes that should stay in the FG.
foregroundWindowPrefixes:
  - "##NotifyMainWindow"

# Game addon -> ImGui window IDs.
defaultPins:
  FieldMarker:
    - 0x3E3947D9 # Waymark Preset Plugin Library
  AreaMap:
    - 0xBA3B099F # QuestAWAY quick enable
  GoldSaucerInfo:
    - 0x5DDFA2F0 # Saucy
    - 0x7EFB6976 # Saucy
  ContentsReplaySetting:
    - 0x1D13E817 # A Realm Recorded
  RetainerList:
    - 0xF9BB4082 # Allagan Market
  RetainerSellList:
    - 0x2E5F7C41 # Allagan Market
    - 0xF3A990BA # MarketBuddy
  RetainerSell:
    - 0x4C909AC4 # Allagan Market
  RecipeNote:
    - 0x64EFA525 # Artisan
    - 0x2268D9F6 # Artisan
  CollectablesShop:
    - 0xAFCD7E2F # Pandora

# Game addons that can be lifted to the FG.
liftableAddons:
  - _ActionCross
  - _ActionDoubleCrossL
  - _ActionDoubleCrossR
  - _BagWidget
  - _PartyList
  - _EnemyList
  - _DTR
  - _ParameterWidget
  - _MainCommand
  - _Money
  - _LimitBreak
  - _FocusTargetInfo
  - _ContentGauge
  - _ToDoList
  - _CastBar
  - _Exp
  - _ActionContents
  - ScenarioTree

# Game addons name prefixes that can be lifted to the FG.
liftableAddonPrefixes:
  - _ActionBar
  - _Status
  - _AllianceList
  - _TargetInfo
  - JobHud
