version: 1

# Deprecated - unused in latest versions
foregroundWindowIds:
  - 0x88AE4BAD # Gaolbreak ###GaolbreakIndicator
  - 0xE73BC75C # ResPls ##rezRects

# Deprecated - unused in latest versions
foregroundWindowPrefixes:
  - "##NotifyMainWindow"
  - "##selectstring"

# Game addon -> ImGui window name regexes
defaultPinPatterns:
  "*":
    - "^##NotifyMainWindow"
    - "^##selectstring"
  GaolbreakRestBeacon:
    - "^PctWindow"

# Game addon -> ImGui window IDs.
defaultPins:
  "*":
    - 0x88AE4BAD # Gaolbreak ###GaolbreakIndicator
    - 0xE73BC75C # ResPls ##rezRects
  FieldMarker:
    - 0x3E3947D9 # Waymark Preset Plugin Library
  AreaMap:
    - 0xBA3B099F # QuestAWAY quick enable
  GoldSaucerInfo:
    - 0x5DDFA2F0 # Saucy
    - 0x7EFB6976 # Saucy
  ContentsReplaySetting:
    - 0x1D13E817 # A Realm Recorded
  RetainerList:
    - 0xF9BB4082 # Allagan Market
    - 0x63256ECB # AutoRetainer
  RetainerSellList:
    - 0x2E5F7C41 # Allagan Market
    - 0xF3A990BA # MarketBuddy
    - 0xDD23A42E # Daily Routines
  RetainerSell:
    - 0x4C909AC4 # Allagan Market
  RecipeNote:
    - 0x64EFA525 # Artisan
    - 0x2268D9F6 # Artisan
  CollectablesShop:
    - 0xAFCD7E2F # Pandora
  LookingForGroupDetail:
    - 0x3ADB2436 # Passport Checker Reborn
  GaolbreakRestBeacon:
    - 0xEC35CAD0 # Distance overlay
